#!/usr/bin/env python3
"""
Generate an animated GitHub contribution SVG.

Uses data/contributions.json generated by fetch_contributions.py,
so the graph and statistics always use the same GitHub data.

Usage:
    python generate_streak_svg.py
    python generate_streak_svg.py sayan629 streak.svg
"""

import sys
import json
import os
import datetime


# ============================================================
# USER / OUTPUT
# ============================================================

USER = (
    sys.argv[1]
    if len(sys.argv) > 1
    else "sayan629"
)

OUT = (
    sys.argv[2]
    if len(sys.argv) > 2
    else "streak.svg"
)


# ============================================================
# PATHS
# ============================================================

SCRIPT_DIR = os.path.dirname(
    os.path.abspath(__file__)
)

BASE_DIR = os.path.dirname(
    SCRIPT_DIR
)

SNAPSHOT = os.path.join(
    BASE_DIR,
    "data",
    "contributions.json"
)


# ============================================================
# LOAD GITHUB DATA
# ============================================================

def get_data(user):

    if not os.path.exists(SNAPSHOT):

        raise FileNotFoundError(
            "contributions.json not found.\n"
            "Run:\n"
            "python scripts/fetch_contributions.py"
        )


    with open(
        SNAPSHOT,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)


    snapshot_user = data.get(
        "username",
        ""
    )


    if snapshot_user.lower() != user.lower():

        raise ValueError(
            f"Snapshot belongs to "
            f"'{snapshot_user}', "
            f"but requested '{user}'."
        )


    return data


# ============================================================
# DATA
# ============================================================

data = get_data(USER)

contribs = data["days"]

total = data["total_contributions"]


# ============================================================
# LAYOUT
# ============================================================

CELL = 13
GAP = 3
RAD = 2.5

LEFT = 34
TOP = 24


# Dark GitHub-style green palette
COLORS = [
    "#161b22",
    "#0e4429",
    "#006d32",
    "#26a641",
    "#39d353",
]


FLASH = "#b4ffaa"

GRAY = "#7d8590"

TEXT = "#e6edf3"

BACKGROUND = "#0d1117"


MONTHS = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
]


# ============================================================
# GRID
# ============================================================

n = len(contribs)

NW = (
    n + 6
) // 7


W = (
    LEFT
    + NW * (CELL + GAP)
    + 6
)


H = (
    TOP
    + 7 * (CELL + GAP)
    + 34
)


# ============================================================
# ANIMATION
# ============================================================

REVEAL = 5.0

DUR = 0.55

maxorder = (
    (NW - 1)
    + 6 * 0.55
)


# ============================================================
# MONTH / WEEKDAY LABELS
# ============================================================

rects = []

labels = []


start_date = datetime.date.fromisoformat(
    contribs[0]["date"]
)


last_month = None


for week in range(NW):

    current_date = (
        start_date
        + datetime.timedelta(
            days=week * 7
        )
    )


    if current_date.month != last_month:

        last_month = (
            current_date.month
        )


        labels.append(
            f'''
<text
    class="lbl"
    x="{LEFT + week * (CELL + GAP)}"
    y="{TOP - 8}">
    {MONTHS[current_date.month - 1]}
</text>
'''
        )


# ============================================================
# WEEKDAY LABELS
# ============================================================

for name, row in [
    ("Mon", 1),
    ("Wed", 3),
    ("Fri", 5)
]:

    labels.append(
        f'''
<text
    class="lbl"
    x="2"
    y="{TOP + row * (CELL + GAP) + CELL - 2}">
    {name}
</text>
'''
    )


# ============================================================
# CONTRIBUTION CELLS
# ============================================================

for i, contribution in enumerate(
    contribs
):

    week = i // 7

    row = i % 7

    level = int(
        contribution.get(
            "level",
            0
        )
    )


    level = max(
        0,
        min(
            4,
            level
        )
    )


    x = (
        LEFT
        + week * (CELL + GAP)
    )


    y = (
        TOP
        + row * (CELL + GAP)
    )


    delay = round(
        (
            week
            + row * 0.55
        )
        / maxorder
        * REVEAL,
        3
    )


    if level >= 1:

        classes = "c g"

    else:

        classes = "c"


    rects.append(
        f'''
<rect
    class="{classes}"
    x="{x}"
    y="{y}"
    width="{CELL}"
    height="{CELL}"
    rx="{RAD}"
    fill="{COLORS[level]}"
    style="animation-delay:{delay}s">

    <title>
        {contribution["count"]} contributions
        on {contribution["date"]}
    </title>

</rect>
'''
    )


# ============================================================
# SVG
# ============================================================

svg = f'''
<svg
    xmlns="http://www.w3.org/2000/svg"
    width="{W}"
    height="{H}"
    viewBox="0 0 {W} {H}"
    font-family="-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif">

<style>

text.lbl {{
    fill: {GRAY};
    font-size: 13px;
    font-weight: 600;
}}

text.total {{
    fill: {TEXT};
    font-size: 15px;
    font-weight: 700;
}}


/* Contribution animation */

.c {{

    transform-box: fill-box;

    transform-origin: center;

    opacity: 0;

    animation:
        pop
        {DUR}s
        ease-out
        both;
}}


/* Active contribution flash */

.g {{

    animation:
        pop
        {DUR}s
        ease-out
        both,

        flash
        {DUR + 0.15}s
        ease-out
        both;
}}


/* Cell reveal */

@keyframes pop {{

    0% {{

        opacity: 0;

        transform:
            scale(0.2);
    }}

    60% {{

        opacity: 1;

        transform:
            scale(1.1);
    }}

    100% {{

        opacity: 1;

        transform:
            scale(1);
    }}

}}


/* Green flash */

@keyframes flash {{

    0% {{

        filter:
            brightness(2.4);
    }}

    45% {{

        filter:
            brightness(2.4);
    }}

    100% {{

        filter:
            brightness(1);
    }}

}}


/* Accessibility */

@media (prefers-reduced-motion: reduce) {{

    .c {{

        opacity: 1 !important;

        animation:
            none !important;
    }}

}}

</style>


<!-- Background -->

<rect
    width="{W}"
    height="{H}"
    rx="10"
    fill="{BACKGROUND}"
/>


<!-- Month / weekday labels -->

{''.join(labels)}


<!-- Contribution cells -->

{''.join(rects)}


<!-- Total -->

<text
    class="total"
    x="{LEFT}"
    y="{H - 7}">
    {total:,} contributions in the last year
</text>


</svg>
'''


# ============================================================
# WRITE SVG
# ============================================================

with open(
    OUT,
    "w",
    encoding="utf-8"
) as file:

    file.write(
        svg
    )


print()

print(
    "======================================"
)

print(
    " GITHUB STREAK SVG CREATED"
)

print(
    "======================================"
)

print()

print(
    f"User          : {USER}"
)

print(
    f"Days          : {n}"
)

print(
    f"Contributions : {total:,}"
)

print(
    f"Output        : {OUT}"
)

print(
    f"Size          : {W} x {H}"
)

print(
    "Animation     : 5 seconds"
)

print()